[skin]
    description = Nord
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ─
    dvert = │
    dlefttop = ┌
    drighttop = ┐
    dleftbottom = └
    drightbottom = ┘
    dtopmiddle = ┬
    dbottommiddle = ┴
    dleftmiddle = ├
    drightmiddle = ┤

[aliases]
    polar0 = #2e3440
    polar1 = #3b4252
    polar2 = #434c5e
    polar3 = #4c566a

    snow4 = #d8dee9
    snow5 = #e5e9f0
    snow6 = #eceff4

    frost7 = #8fbcbb
    frost8 = #88c0d0
    frost9 = #81a1c1
    frost10 = #5e81ac

    black = #000000
    red = #bf616a
    orange = #d08770
    yellow = #ebcb8b
    green = #a3be8c
    purple = #b48ead

[core]
    _default_ = snow4;polar0
    selected = snow5;red
    marked = yellow;polar0
    markselect = yellow;red
    gauge = polar0;snow5
    input = frost9;polar0
    inputmark = frost9;polar3
    inputunchanged = polar3;polar0
    commandlinemark = polar0;snow4
    reverse = yellow;polar0
    header = snow5;polar0
    disabled = polar3;polar0
    shadow = polar1;black

[dialog]
    _default_ = snow5;polar1
    dhotnormal = yellow;polar1
    dhotfocus = yellow;red
    dfocus = snow5;red
    dtitle = yellow;polar1

[error]
    _default_ = snow5;red
    errdfocus = snow5;orange
    errdhotnormal = yellow;red
    errdhotfocus = yellow;orange
    errdtitle = yellow;red

[filehighlight]
    directory   = frost8;;bold
    executable  = #99cc66;
    symlink     = #66cccc;
    hardlink    = #66cccc;
    stalelink   = #cc6666;
    device      = #cc9933;
    special     = #cc66cc;
    core        = #aaaaaa;
    temp        = #888888;
    archive     = #ff6666;
    doc         = #ffffff;
    source      = #88ccff;
    media       = #cc66cc;
    graph       = #cc66cc;
    database    = #ffcc66;

[menu]
    _default_ = snow5;polar1
    menusel = snow5;red
    menuhot = yellow;polar1
    menuhotsel = yellow;red
    menuinactive = snow4;polar1

[popupmenu]
    _default_ = snow5;polar1
    menusel = snow5;red
    menutitle = yellow;polar1

[buttonbar]
    button = snow4;polar2
    hotkey = yellow;default

[statusbar]
    _default_ = yellow;polar2

[help]
    _default_ = snow5;polar1
    helpitalic = yellow;polar1;italic
    helpbold = snow6;polar1;bold
    helplink = frost8;polar1
    helpslink = snow5;frost9
    helptitle = yellow;polar1

[editor]
    _default_ = ;default
    editbold = ;;bold
    editmarked = ;polar3
    editwhitespace = ;red
    editnonprintable = ;black
    editlinestate = ;polar0
    bookmark = snow5;red
    bookmarkfound = snow5;polar3
    editrightmargin = ;polar0
#   editframe =
    editframeactive = frost8;
    editframedrag = frost9;

[viewer]
    _default_ = snow4;
    viewbold = yellow;;bold
    viewunderline = orange;;underline
    viewselected = yellow;polar3

[diffviewer]
    changedline = ;polar1
    changednew = polar3;yellow
    changed = ;polar1
    added = ;green
    removed = ;red
    error = red;polar3

[widget-common]
    sort-sign-up = 
    sort-sign-down = 

[widget-panel]
    sort-up-char = 
    sort-down-char = 
    hiddenfiles-show-char = ∙
    hiddenfiles-hide-char = ∙
    history-prev-item-char = 
    history-next-item-char = 
    history-show-list-char = 
    filename-scroll-left-char = 
    filename-scroll-right-char = 

[widget-editor]
    window-state-char = 󰖲
    window-close-char = 
