#!/bin/sh
set -e

case "$1" in
    configure)
        mkdir -p /etc/skel/.bashrc.d /etc/skel/.profile.d

        dpkg-divert --package cccp-standard-meta --add --rename \
            --divert /etc/bashrc.distrib /etc/bash.bashrc

        dpkg-divert --package cccp-standard-meta --add --rename \
            --divert /etc/skel/.bashrc.distrib /etc/skel/.bashrc
        dpkg-divert --package cccp-standard-meta --add --rename \
            --divert /etc/skel/.profile.distrib /etc/skel/.profile

        cp /usr/share/cccp-meta/etc.bashrc   /etc/bash.bashrc
        cp /usr/share/cccp-meta/skel.bashrc  /etc/skel/.bashrc
        cp /usr/share/cccp-meta/skel.profile /etc/skel/.profile
        ;;

    abort-upgrade|abort-remove|abort-deconfigure|triggered) ;;

    *) echo "postinst called with unknown argument '$1'" >&2 ; exit 1 ;;
esac

#DEBHELPER#

exit 0
